---

name: container image

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: 0 0 * * 1     # weekly

jobs:
  docker_publish:
    runs-on: "ubuntu-latest"

    steps:
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v2
      #
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Build only
        uses: docker/build-push-action@v3
        if: github.event_name == 'pull_request'
        with:
          push: false
          file: ./Containerfile
          tags: brightpick/ra:openvpn-client-latest

      - name: Build and push
        uses: docker/build-push-action@v3
        if: github.event_name != 'pull_request'
        with:
          push: true
          file: ./Containerfile
          tags: brightpick/ra:openvpn-client-latest
