---

name: build and publish the image to ghcr.io

on:
  push:
    branches:
      - main
  schedule:
    - cron: 0 0 * * 1     # weekly

jobs:
  docker_publish:
    runs-on: "ubuntu-20.04"

    steps:
      - uses: actions/checkout@v2

      - name: build and publish
        uses: macbre/push-to-ghcr@master
        with:
          image_name: ${{ github.repository }}
          image_tag: latest
          dockerfile: ./Containerfile
          github_token: ${{ secrets.GITHUB_TOKEN }}
